---
# tasks file for roles/osp-instance-delete
#  - name: Fetch Instance Info
- name: Delete instances
  os_server:
    cloud: ospcloud
    name: "{{ instance_name }}"
    state: absent
    delete_fip: yes   
