# Only bastion could be login with SSS, when not using "Creds for AWS instances" credential
- hosts: tag_AnsibleGroup_bastions
  gather_facts: true
  become: yes
  tasks:

  - name: Show inventory_hostname
    debug: var=inventory_hostname

  - name: Show localhost
    debug: var=localhost

  - name: Check the instances status
    wait_for:
      host: inventory_hostname
      port: 22
      search_regex: OpenSSH
      timeout: 600
    delegate_to: localhost

  - name: Show public IP
    debug: var=ansible_host     
