- hosts: tag_instance_filter_three_tier_app_haizhang_redhat_com
  gather_facts: true
  become: yes
  tasks:
#  - name: Check the instances status
#    wait_for:
#      host: "{{ item }}"
#      port: 22
#      search_regex: OpenSSH
#      timeout: 600
#    delegate_to: localhost
#    with_items:
#      - "{{ inventory_hostname }}"
  - name: Show public IP
    debug: var=ansible_host     
