- hosts: tag_AnsibleGroup_bastions
  gather_facts: true
#  roles:
#  - name: osp-facts

# Setup front-end load balancer tier


- name: setup load-balancer tier
  hosts: tag_AnsibleGroup_frontends
  become: yes
  roles:
    - {name: base-config, tags: base-config}
    - {name: lb-tier, tags: [lbs, haproxy]}

# Setup application servers tier

- name: setup app tier
  hosts: tag_AnsibleGroup_apps
  become: yes
  gather_facts: true
  roles:
    - {name: base-config, tags: base-config}
    - {name: app-tier, tags: [apps, tomcat]}

# Setup database tier

- name: setup database tier
  become: yes
  hosts: tag_AnsibleGroup_appdbs
  roles:
    - {name: base-config, tags: base-config}
    - {name: db-tier, tags: [dbs, postgres]}
