---
# tasks file for db-tier
- name: install postgres
  yum:
    name: "{{ postgres_pkg_name }}"
    state: latest

- name: enable apache at boot
  service:
    name:  "{{ postgres_srv_name }}"
    enabled: yes

# test postgresql Initialization
- name: Check database initialization
  command: postgresql-check-db-dir  /var/lib/pgsql/data
  register: check_db_output
  changed_when: check_db_output == 1
  ignore_errors: yes

- name: initilize postgres, only run the these 2 tasks once!
  shell: postgresql-setup initdb
  # shell: chkconfig postgresql on
  when: check_db_output.rc != 0

- name: start postgres
  service:
    name: "{{ postgres_srv_name }}"
    state: started
